AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2

# Use trailing rather than leading dots on multi-line call chains
Layout/DotPosition:
  EnforcedStyle: trailing

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Naming/AccessorMethodName:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/GlobalVars:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
