language: ruby

rvm:
  - 3.0.0-preview1
  - 2.7.1
  - 2.6.6
  - 2.5.8

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'CREATE DATABASE safer_migrations_test;' -U postgres

script:
  - bundle exec rspec spec
  - bundle exec rubocop

env:
  global:
    - "DATABASE_URL=postgres://postgres@localhost/safer_migrations_test"
  matrix:
    - "ACTIVERECORD_VERSION=4.2.9"
    - "ACTIVERECORD_VERSION=5.0.5"
    - "ACTIVERECORD_VERSION=5.1.3"
