language: ruby

rvm:
  - 2.3.4
  - 2.2.6
  - 2.1.10
  - 2.0.0-p648

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'CREATE DATABASE safer_migrations_test;' -U postgres

script:
  - bundle exec rspec spec
  - bundle exec rubocop

env:
  global:
    - "DATABASE_URL=postgres://postgres@localhost/safer_migrations_test"
  matrix:
    - "ACTIVERECORD_VERSION=4.0.13"
    - "ACTIVERECORD_VERSION=4.1.16"
    - "ACTIVERECORD_VERSION=4.2.8"
    - "ACTIVERECORD_VERSION=5.0.3"
    - "ACTIVERECORD_VERSION=5.1.1"

matrix:
  exclude:
    - rvm: 2.1.10
      env: "ACTIVERECORD_VERSION=5.0.3"
    - rvm: 2.0.0-p648
      env: "ACTIVERECORD_VERSION=5.0.3"
    - rvm: 2.1.10
      env: "ACTIVERECORD_VERSION=5.1.1"
    - rvm: 2.0.0-p648
      env: "ACTIVERECORD_VERSION=5.1.1"
